name = "projectNEWM/newm-minter"
version = "1.0.2"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "GPL-3.0-or-later"
description = "Project NEWM's Fractional Minting Contract"

[repository]
user = "projectNEWM"
project = "newm-minter"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.4.10"
source = "github"